# Use the official Python 3.7 image as the base image
FROM python:3.11

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Specify the command to run your application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
